import { AlignmentType, Document, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from "docx";

function safeText(value, fallback = "") {
  return String(value ?? fallback).trim();
}

function formatStudentCell(studentName, studentNumber) {
  const name = safeText(studentName, "Unknown");
  const number = safeText(studentNumber, "");
  const lines = [name];
  if (number) lines.push(number);
  return lines.join("\n");
}

function formatViolationCell(offenseNumber, offenseClassification, specificViolation) {
  const parts = [];
  const offenseNo = safeText(offenseNumber, "");
  if (offenseNo) parts.push(`Offense No.: ${offenseNo}`);
  const classification = safeText(offenseClassification, "Unspecified");
  if (classification) parts.push(`Classification: ${classification}`);
  const specific = safeText(specificViolation, "Unspecified");
  if (specific) parts.push(`Violation: ${specific}`);
  return parts.join("\n");
}

function formatOutcomeCell(sanctionRecommended, status) {
  const parts = [];
  const sanction = safeText(sanctionRecommended, "N/A");
  if (sanction) parts.push(`Sanction: ${sanction}`);
  const currentStatus = safeText(status, "N/A");
  if (currentStatus) parts.push(`Status: ${currentStatus}`);
  return parts.join("\n");
}

export function createReportsDocx(headers = [], rows = []) {
  const visibleHeaders = ["Date", "Student", "Violation", "Outcome"];
  const visibleRows = rows.map((row) => {
    const [date, studentNumber, studentName, gradeLevel, offenseClassification, specificViolation, offenseNumber, sanctionRecommended, status] = row;
    return [
      safeText(date, "N/A"),
      formatStudentCell(studentName, studentNumber),
      formatViolationCell(offenseNumber, [offenseClassification, gradeLevel].filter(Boolean).join(" / "), specificViolation),
      formatOutcomeCell(sanctionRecommended, status),
    ];
  });

  const tableRows = [
    new TableRow({
      children: visibleHeaders.map((header) => new TableCell({
        shading: { fill: "D9E2F3" },
        children: [
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: header, bold: true })],
          }),
        ],
      })),
    }),
    ...visibleRows.map((row) => new TableRow({
      children: row.map((value) => new TableCell({
        verticalAlign: "center",
        children: [
          new Paragraph({
            spacing: { after: 0 },
            children: value.split("\n").map((line) => new TextRun({ text: line, break: line !== value.split("\n")[0] ? 1 : 0 })),
          }),
        ],
      })),
    })),
  ];

  return new Document({
    title: "SARES Incident Report Summary",
    description: "Disciplinary violation summary generated by SARES.",
    sections: [{
      children: [
        new Paragraph({
          text: "SARES Incident Report Summary",
          heading: "Heading1",
          spacing: { after: 200 },
        }),
        new Paragraph({
          text: "This report includes the student grade level for each recorded incident.",
          spacing: { after: 200 },
        }),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: tableRows,
        }),
      ],
    }],
  });
}

export async function generateReportsDocx(headers = [], rows = [], fileName = "sares-reports.docx") {
  const doc = createReportsDocx(headers, rows);
  const blob = await Packer.toBlob(doc);
  const rootDocument = typeof document !== "undefined" ? document : null;

  if (rootDocument) {
    const url = URL.createObjectURL(blob);
    const link = rootDocument.createElement("a");
    link.href = url;
    link.download = fileName;
    rootDocument.body.appendChild(link);
    link.click();
    rootDocument.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  return blob;
}

export const createReportsXlsx = createReportsDocx;